# This is an example configuration. Lines starting with # are comments and are ignored.
# 
# settings:
#   anti-xray:
#     update-ticks: 1                           # Time period in Minecraft ticks for sending block updates.
#     ms-per-ray-trace-tick: 50                 # Target time per ray trace tick in milliseconds.
#     ray-trace-threads: 2                      # Number of threads that are used for ray tracing.
# world-settings:
#   default:                                    # All worlds inherit settings from the `default` section.
#     anti-xray:
#       ray-trace: true                         # Whether or not to enable ray tracing. Note that Paper Anti-Xray must also be enabled using 'engine-mode: 1'.
#       ray-trace-third-person: true            # Whether or not to ray trace third person back and front view. Note that this is even more resource intensive.
#       ray-trace-distance: 64.0                # Maximum distance between player (eye location) and block (center) for ray tracing.
#       max-ray-trace-block-count-per-chunk: 30 # Maximum number of ray traced blocks per chunk. Counting starts at the bottom of the world and increases upwards.
#       ray-trace-blocks:                       # Blocks that are hidden and ray traced. The `hidden-blocks` specified in the Paper config file are only hidden if they aren't exposed to transparent blocks. If this list is empty, the `hidden-blocks` specified in the Paper config file are used.
#       - diamond_ore
#       - deepslate_diamond_ore
#       - emerald_ore
#       - deepslate_emerald_ore
#   lobby:                                      # Example section for the world 'lobby'. Missing settings are inherited from the `default` section.
#     anti-xray:
#       ray-trace: false                        # Disable ray tracing in the world 'lobby'.

settings:
  anti-xray:
    update-ticks: 1
    ms-per-ray-trace-tick: 50
    ray-trace-threads: 2
world-settings:
  default:
    anti-xray:
      ray-trace: true
      ray-trace-third-person: false
      ray-trace-distance: 80.0
      max-ray-trace-block-count-per-chunk: 100
      ray-trace-blocks: []
